### PR TITLE
Add a new method "addFromUrl"

### PR DESCRIPTION
**Pull request by romaincazier**
In a project I'm currently working on I needed a function to add an image from a URL using the API.

I came across your module and extracted the bit I was interested in and created a hook method out of it. However I thought it might be a good addition to your module as well so I decided to go ahead and propose this PR.

I extracted the loop adding the URLs to the Pagefiles(/images) to its own dedicated function and called it from both your `processInput` hook and the new hook method `addFromUrl`.

The idea for this method is to accept a single URL string, multiple URLs separated by commas or an array of URLs.

Please have a look and don't hesitate to edit if need be!

### CODE REVIEW

**Comment by Toutouwai** [comment]
Thanks for this contribution. Could you please also update the readme to include an explanation/example for the `addFromUrl()` method you've added?

The error feedback assumes the code is executing in the PW admin. If somebody is using `addFromUrl()` outside of the admin they wont see any error feedback. Not sure if you see that as a problem or not. Maybe mention that in your documentation for the method?

**Comment by romaincazier** [comment]
Thank you for your feedback. I went ahead and added an argument to the `addUrlsToField` to specify if it's from the API or not. If so then it prints the warnings/errors to the log files instead. I added a mention to these in the README.

Let me know if you feel something else is missing.

**Comment by Toutouwai** [comment]
Thanks @romaincazier, great work! I made a couple of minor tweaks before merging:
* I updated the PhpDoc for `addUrlsToField` to indicate that `$from_api` means errors are logged rather than WireExceptions thrown
* I changed back to `addHookMethod` because this is more descriptive and I believe it is Ryan's preference that this method be used in third-party code because `addHook` is undocumented and flagged `#pw-internal`

Thanks again!

**Comment by romaincazier** [comment]
Sounds good, and glad to have contributed!

**Pull request merged**
